
services:
  mcp-test:
    build: .
    image: gundam/mcp-test:1.0.0
    container_name: mcp-test
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    restart: unless-stopped
    networks:
      - mcp-network
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - FASTMCP_PORT=8000
      - FASTMCP_TRANSPORT=sse
      - FASTMCP_DEBUG=true
      - FASTMCP_HOST=0.0.0.0
networks:
  mcp-network:
    driver: bridge